import model.Coef

fun getAnsw(): MutableList<Double> =
    mutableListOf<Double>().apply {
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(82.toDouble())
        add(153.toDouble())
        add(80.toDouble())
        add(1.toDouble())
        add(2.toDouble())
        add(123.toDouble())
        add(150.toDouble())
        add(93.toDouble())
        add(6.toDouble())
        add(7.toDouble())
        add(189.toDouble())
        add(200.toDouble())
        add(103.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(105.toDouble())
        add(178.toDouble())
        add(98.toDouble())
        add(7.toDouble())
    }

fun getTestW(): MutableList<Double> =
    mutableListOf<Double>().apply {
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(7.toDouble())
        add(8.toDouble())
        add(9.toDouble())
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(7.toDouble())
        add(8.toDouble())
        add(9.toDouble())
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(7.toDouble())
    }

fun getCoefs(): MutableList<Coef> = mutableListOf<Coef>().apply {
    add(Coef(1.toDouble(), 1, 1))
    add(Coef(1.toDouble(), 2, 2))
    add(Coef(1.toDouble(), 3, 3))
    add(Coef(1.toDouble(), 4, 4))
    add(Coef(1.toDouble(), 5, 5))
    add(Coef(1.toDouble(), 6, 6))
    add(Coef(200.toDouble(), 7, 7))
    add(Coef(7.toDouble(), 8, 7))
    add(Coef(600.toDouble(), 8, 8))
    add(Coef(4.toDouble(), 9, 8))
    add(Coef(200.toDouble(), 9, 9))
    add(Coef(1.toDouble(), 10, 10))
    add(Coef(1.toDouble(), 11, 11))
    add(Coef(4.toDouble(), 12, 7))
    add(Coef(500.toDouble(), 12, 12))
    add(Coef(5.toDouble(), 13, 8))
    add(Coef(4.toDouble(), 13, 12))
    add(Coef(500.toDouble(), 13, 13))
    add(Coef(6.toDouble(), 14, 9))
    add(Coef(3.toDouble(), 14, 13))
    add(Coef(500.toDouble(), 14, 14))
    add(Coef(1.toDouble(), 15, 15))
    add(Coef(1.toDouble(), 16, 16))
    add(Coef(8.toDouble(), 17, 12))
    add(Coef(800.toDouble(), 17, 17))
    add(Coef(7.toDouble(), 18, 13))
    add(Coef(9.toDouble(), 18, 17))
    add(Coef(700.toDouble(), 18, 18))
    add(Coef(2.toDouble(), 19, 14))
    add(Coef(7.toDouble(), 19, 18))
    add(Coef(600.toDouble(), 19, 19))
    add(Coef(1.toDouble(), 20, 20))
    add(Coef(1.toDouble(), 21, 21))
    add(Coef(5.toDouble(), 22, 17))
    add(Coef(500.toDouble(), 22, 22))
    add(Coef(6.toDouble(), 23, 18))
    add(Coef(9.toDouble(), 23, 22))
    add(Coef(800.toDouble(), 23, 23))
    add(Coef(4.toDouble(), 24, 19))
    add(Coef(8.toDouble(), 24, 23))
    add(Coef(900.toDouble(), 24, 24))
    add(Coef(1.toDouble(), 25, 25))
}

fun getRight(): List<Double> = mutableListOf<Double>().apply {
    add(1.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(4.toDouble())
    add(5.toDouble())
    add(6.toDouble())
    add(1468.toDouble())
    add(4905.toDouble())
    add(1862.toDouble())
    add(1.toDouble())
    add(2.toDouble())
    add(1608.toDouble())
    add(2130.toDouble())
    add(2568.toDouble())
    add(6.toDouble())
    add(7.toDouble())
    add(6525.toDouble())
    add(6437.toDouble())
    add(697.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(2085.toDouble())
    add(4138.toDouble())
    add(5444.toDouble())
    add(7.toDouble())
}

fun getRightForTransp(): List<Double> = mutableListOf<Double>().apply {
    add(1.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(4.toDouble())
    add(5.toDouble())
    add(6.toDouble())
    add(82.toDouble())
    add(104.toDouble())
    add(48.toDouble())
    add(1.toDouble())
    add(2.toDouble())
    add(95.toDouble())
    add(98.toDouble())
    add(27.toDouble())
    add(6.toDouble())
    add(7.toDouble())
    add(165.toDouble())
    add(100.toDouble())
    add(30.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(65.toDouble())
    add(88.toDouble())
    add(54.toDouble())
    add(7.toDouble())
}