fun getAnsw(): MutableList<Double> =
    mutableListOf<Double>().apply {
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(82.toDouble())
        add(153.toDouble())
        add(80.toDouble())
        add(1.toDouble())
        add(2.toDouble())
        add(123.toDouble())
        add(150.toDouble())
        add(93.toDouble())
        add(6.toDouble())
        add(7.toDouble())
        add(189.toDouble())
        add(200.toDouble())
        add(103.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(105.toDouble())
        add(178.toDouble())
        add(98.toDouble())
        add(7.toDouble())
    }

fun getTestW(): MutableList<Double> =
    mutableListOf<Double>().apply {
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(7.toDouble())
        add(8.toDouble())
        add(9.toDouble())
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(7.toDouble())
        add(8.toDouble())
        add(9.toDouble())
        add(1.toDouble())
        add(2.toDouble())
        add(3.toDouble())
        add(4.toDouble())
        add(5.toDouble())
        add(6.toDouble())
        add(7.toDouble())
    }

fun getCoefs(): Map<Pair<Int, Int>, Double> = mutableMapOf<Pair<Int, Int>, Double>().apply {

    set(Pair(1, 1), 1.toDouble())
    set(Pair(2, 2), 1.toDouble())
    set(Pair(3, 3), 1.toDouble())
    set(Pair(4, 4), 1.toDouble())
    set(Pair(5, 5), 1.toDouble())
    set(Pair(6, 6), 1.toDouble())
    set(Pair(7, 7), 200.toDouble())
    set(Pair(8, 7), 7.toDouble())
    set(Pair(8, 8), 600.toDouble())
    set(Pair(9, 8), 4.toDouble())
    set(Pair(9, 9), 200.toDouble())
    set(Pair(10, 10), 1.toDouble())
    set(Pair(11, 11), 1.toDouble())
    set(Pair(12, 7), 4.toDouble())
    set(Pair(12, 12), 500.toDouble())
    set(Pair(13, 8), 5.toDouble())
    set(Pair(13, 12), 4.toDouble())
    set(Pair(13, 13), 500.toDouble())
    set(Pair(14, 9), 6.toDouble())
    set(Pair(14, 13), 3.toDouble())
    set(Pair(14, 14), 500.toDouble())
    set(Pair(15, 15), 1.toDouble())
    set(Pair(16, 16), 1.toDouble())
    set(Pair(17, 12), 8.toDouble())
    set(Pair(17, 17), 800.toDouble())
    set(Pair(18, 13), 7.toDouble())
    set(Pair(18, 17), 9.toDouble())
    set(Pair(18, 18), 700.toDouble())
    set(Pair(19, 14), 2.toDouble())
    set(Pair(19, 18), 7.toDouble())
    set(Pair(19, 19), 600.toDouble())
    set(Pair(20, 20), 1.toDouble())
    set(Pair(21, 21), 1.toDouble())
    set(Pair(22, 17), 5.toDouble())
    set(Pair(22, 22), 500.toDouble())
    set(Pair(23, 18), 6.toDouble())
    set(Pair(23, 22), 9.toDouble())
    set(Pair(23, 23), 800.toDouble())
    set(Pair(24, 19), 4.toDouble())
    set(Pair(24, 23), 8.toDouble())
    set(Pair(24, 24), 900.toDouble())
    set(Pair(25, 25), 1.toDouble())
}

fun getRight(): List<Double> = mutableListOf<Double>().apply {
    add(1.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(4.toDouble())
    add(5.toDouble())
    add(6.toDouble())
    add(1468.toDouble())
    add(4905.toDouble())
    add(1862.toDouble())
    add(1.toDouble())
    add(2.toDouble())
    add(1608.toDouble())
    add(2130.toDouble())
    add(2568.toDouble())
    add(6.toDouble())
    add(7.toDouble())
    add(6525.toDouble())
    add(6437.toDouble())
    add(697.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(2085.toDouble())
    add(4138.toDouble())
    add(5444.toDouble())
    add(7.toDouble())
}

fun getRightForTransp(): List<Double> = mutableListOf<Double>().apply {
    add(1.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(4.toDouble())
    add(5.toDouble())
    add(6.toDouble())
    add(82.toDouble())
    add(104.toDouble())
    add(48.toDouble())
    add(1.toDouble())
    add(2.toDouble())
    add(95.toDouble())
    add(98.toDouble())
    add(27.toDouble())
    add(6.toDouble())
    add(7.toDouble())
    add(165.toDouble())
    add(100.toDouble())
    add(30.toDouble())
    add(2.toDouble())
    add(3.toDouble())
    add(65.toDouble())
    add(88.toDouble())
    add(54.toDouble())
    add(7.toDouble())
}